### PR TITLE
Bump version from 3.5.0 to 3.6.0

### PR DESCRIPTION
**Pull request by rvl**
Updates Cabal file versions for a release, and also bumps the Stackage LTS snapshot.

### CODE REVIEW

**Review by piotr-iohk — APPROVED** [review]
Ok, except NPM build failing I guess.

**Comment by rvl** [comment]
I updated the branch to remove the GHC 8.10.7 bump (now in PR #148) - that should fix the NPM build I hope.

**Comment by piotr-iohk** [comment]
>I updated the branch to remove the GHC 8.10.7 bump (now in PR #148) - that should fix the NPM build I hope.

Still failing :thinking:

**Comment by rvl** [comment]
Oh, it was a typo - should have been `cardano-addresses-jsapi` not `cardano-address-jsapi` in `jsapi/package.yaml`.

**Comment by rvl** [comment]
Thanks @piotr-iohk

**Pull request merged**
