### PR TITLE
inspectAddress: Fix address HRP

### PR DESCRIPTION
**Pull request by rvl**
## Issue

ADP-744

## Description

Fixes incorrect network tag check for `inspectAddress`, doh.

Turns out #110 did not add any tests for `inspectAddress`, and there weren't any to begin with.

## TODO

- [x] Golden tests for `inspectAddress` forthcoming.

### CODE REVIEW

**Comment by reactormonk** [comment]
Then https://github.com/input-output-hk/cardano-addresses/pull/110/files#diff-3dc15004d825bd0bb5a3bda11c04a14952a24dc34d32cd52d3fae69c9f9c4e81R129-R132 is wrong too?

**Comment by rvl** [comment]
Nope - that one is correct... though the code is in the wrong module. The one I added was incorrect :-)

**Comment by reactormonk** [comment]
Why does git make a diff of the golden tests? Any whitespace removal happening?

**Review by paweljakubas — APPROVED** [review]
lgtm

**Comment by rvl** [comment]
Thanks @reactormonk @paweljakubas !

I believe the whitespace diff is due to us using different versions of certain Hackage packages.

**Pull request merged**
