### PR TITLE
Use latest ghcjs

### PR DESCRIPTION
**Pull request by hamishmack**
This includes https://github.com/ghcjs/ghcjs/commit/2da23efdeb02b0570fd0693ec1610287f785f042 and https://github.com/ghcjs/ghcjs/commit/e4cd4232a31f6371c761acd93853702f4c7ca74c to fix the duplicates in `rts.js`.

### CODE REVIEW

**Review by rvl — APPROVED** [review]
Sweet, thanks!

**Comment by rvl** [comment]
It looks like the ghcjs build is failing at the `lens` dependency, @hamishmack. I wonder why it would fail like that? If we set index-state, most versions should stay this same.

**Comment by luite** [comment]
I don't think the `lens` failure is related to this pull request. Rerunning the job might well fix it. Unfortunately there's still a bug in ghcjs that causes intermittent typechecker failures like this.

I hope we can fix that soon, since this is quite annoying, especially in situations with CI.

**Comment by hamishmack** [comment]
@rvl restarting the jobs on hydra did seem to fix this one.

**Comment by rvl** [comment]
OK thanks, yes I also hope we can fix this intermittent typechecker failure issue in ghcjs.

**Pull request merged**
